set up linter
LOctavio/members-only pull request #1
Opened 2020-06-19 14:55 UTC by LOctavio

2020-06-23 18:54 UTC, Forison reviewed
## Status:: Change required❌ 
# 🙋‍♂️ Team
* [ ] The routes should be limited to ```resources :posts, only: [:new, :create, :index]``` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- Currently, you have extra routes which are not needed per the requirement of this project.

* [ ] It uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- This will enforce that a user should be signed in before they can create a post
###### `new`
* [ ] it initializes an empty post `@post = Post.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
### That is it, kindly make the changes and submit the project for re-review😎.
#### Happy coding👨🏾‍💻 
#### Addo Forison

2020-06-23 19:53 UTC, nurislam-ab commented
> ## Status:: Change required❌
> # 🙋‍♂️ Team
> * [ ]  The routes should be limited to `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> 
> * Currently, you have extra routes which are not needed per the requirement of this project.
> 

okay we will do that



> * [ ]  It uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

not clear, need more details about this part http://joxi.ru/ZrJoznBtMBzGVm. what kind of helper methods should be created in the ApplicationController?


> * This will enforce that a user should be signed in before they can create a post
> 
but it is already done https://monosnap.com/file/wuJ7qDfduXNewuvcLucY6KRS2bIKrT

if the user clicks the **new post**, they are asked to log in firstly 

following the instructions the before_action was added at the top of the PostController 
http://joxi.ru/8AnnE8aU7JGMVA - odin 
http://joxi.ru/Dr87RwaUz8WbwA - code


> ###### `new`
> * [ ]  it initializes an empty post `@post = Post.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
> 
not clear, why we need that empty instance of the post?

2020-06-23 21:12 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi Team! 👋 

Great job!
One thing though! You did not address the changes the previous reviewer requested correctly. Hopefully, you can understand now what was requested and why.

These are minor and you should be able to get the 👍  after! 😄 

#### Required changes
- See review comments not marked by [OPTIONAL]

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-23 21:12 UTC, mcrd25 commented on app/controllers/posts_controller.rb
> +    @post = Post.new
this is usually found in #new action [OPTIONAL]

2020-06-23 21:12 UTC, mcrd25 commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build
better to say '@post = Post.new`

2020-06-23 21:12 UTC, mcrd25 commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build
You're doing the current_user.posts.build in create, this is not necessary. `@post = Post.new` is simply to initialise the @post variable type

2020-06-23 21:12 UTC, mcrd25 commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, only: %i[new create]
This should be in `PostController` See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) form odin.

2020-06-24 01:38 UTC, Ispirett approved these changes
## Status Approved 🥇 

Great job folks with all changes made and completing this project 👍  You can now move on.

2020-06-25 17:03 UTC, merged